export const RESPONSE_MESSAGE = {
  BASE_ROUTE: "This is the base route",
  NOT_FOUND: "The requested resource was not found",
  INTERNAL_SERVER_ERROR: "Internal server error",
  EMAIL_EXISTS: "Email already exists",
  EMAIL_NOT_EXISTS: "Email do not exits",
  PASSWORD_NOT_MATCH: "Password and confirm password should be same",
  REGISTRATION_SUCCESSFUL: "Registration successful",
  SOMETHING_WENT_WRONG: "Something went wrong.Please try again later",
  WRONG_CREDENTIAL: "Wrong credential",
  SIGN_IN_SUCCESSFUL: "Sign In successful",
  EMAIL_VERIFIED: "Email verified successfully.Please login",
  ACCESS_TOKEN_GENERATED: "Access token generated successfully",
  LOGIN_AGAIN: "Please login again.",
  UNAUTHORIZED_ACCESS: "Unauthorized access.",
  NO_DATA: "No data found",
  SUCCESSFULLY_GET_ALL_DATA: "Successfully get the data",
};
